const environment = {
  dev: {
    DATABASE: "extra_slip",
    USER: "root",
    HOST: "localhost",
    PASSWORD: "",
    DB_PORT: "3306",
    SECRET_KEY: "(?9n%]9Q*k[,,.\vJ89-",
    EMAIL_FROM: "info@extraslip.com",
    EMAIL_PASSWORD: "Vtcx[7sE",
    EMAIL_HOST: "smtp.hostinger.com",
    EMAIL_SERVICE: "Hostinger",
    EMAIL_PORT: "465",
    BASE_URL: "http://localhost:8000",
    MAIL_BASE_URL: "http://localhost:3000",
    CLOUD_NAME: "dxsf7nhsj",
    CLOUDINARY_API_KEY: "118123687597686",
    CLOUDINARY_API_SECRET: "cKKqtLCUm3dwi4cPMczWDsb1nfo",
  },
  test: {
    DATABASE: "extra_slip_staging",
    USER: "extra_slip_user",
    HOST: "localhost",
    PASSWORD: "User!234",
    DB_PORT: "3306",
    SECRET_KEY: "(?9n%]9Q*k[,,.\vJ89-",
    EMAIL_FROM: "info@extraslip.com",
    EMAIL_PASSWORD: "Vtcx[7sE",
    EMAIL_HOST: "smtp.hostinger.com",
    EMAIL_SERVICE: "Hostinger",
    EMAIL_PORT: "465",
    BASE_URL: "https://api.midcricket.com",
    MAIL_BASE_URL: "https://admin.midcricket.com",
    CLOUD_NAME: "dxsf7nhsj",
    CLOUDINARY_API_KEY: "118123687597686",
    CLOUDINARY_API_SECRET: "cKKqtLCUm3dwi4cPMczWDsb1nfo",
  },
  prod: {
    DATABASE: "extra_slip",
    USER: "extra_slip_user",
    HOST: "localhost",
    PASSWORD: "User!234",
    DB_PORT: "3306",
    SECRET_KEY: "(?9n%]9Q*k[,,.\vJ89-",
    EMAIL_FROM: "info@extraslip.com",
    EMAIL_PASSWORD: "Vtcx[7sE",
    EMAIL_HOST: "smtp.hostinger.com",
    EMAIL_SERVICE: "Hostinger",
    EMAIL_PORT: "465",
    BASE_URL: "https://api.midcricket.com",
    MAIL_BASE_URL: "https://admin.midcricket.com",
    CLOUD_NAME: "dxsf7nhsj",
    CLOUDINARY_API_KEY: "118123687597686",
    CLOUDINARY_API_SECRET: "cKKqtLCUm3dwi4cPMczWDsb1nfo",
  },
};

module.exports = environment;
